window_prefix: wm-

panes:
  - command: <agent>
    focus: true
  - command: devbox run -- make run
    split: horizontal

files:
  symlink:
    - node_modules

agent: claude --dangerously-load-development-channels plugin:monocle@monocle
nerdfont: true
